@startuml
title a title
object Object01
object Object02
object Object03
object Object04

Object01 <|-- Object02
Object03 *-- Object04

Object01 : name = "Dummy"
Object01 : +id

newpage
object Object05
object Object06
object Object07
object Object08
Object05 o-- "4" Object06
Object07 .. Object08 : some labels
@enduml